PG_VOCAB_SIZE = 5370
PG_SEQ_LENGTH = 22

# These are char level
PTB_VOCAB_SIZE = 50
PTB_SEQ_LENGTH = 492

DATASET = 'pg'

HIDDEN_STATE_SIZE = 100

BATCH_SIZE = 32
N_CLASSES = 2
LEARNING_RATE_G = 0.01
LEARNING_RATE_D = 0.01
N_EPOCHS = 7


# sanity checks:
DATASET_LIST = ['ptb', 'pg']
assert DATASET in DATASET_LIST